//! SSOT sync logic: reads `meta/project.toml` and regenerates managed files.
//!
//! Managed files:
//! - top-level `Cargo.toml` (`[workspace.package]` block)
//! - `bindings/python/pyproject.toml` (wholly generated)
//! - `bindings/node/package.json` (wholly generated)
//!
//! Every regenerated file uses LF line endings and ends with a single newline.
#![warn(missing_docs)]

use std::path::{Path, PathBuf};

use toml::Value;

// ---------------------------------------------------------------------------
// SSOT types
// ---------------------------------------------------------------------------

/// Parsed contents of `meta/project.toml`.
#[derive(Debug, Clone, PartialEq)]
pub struct ProjectMeta {
    /// Package / distribution name.
    pub name: String,
    /// `SemVer` version string.
    pub version: String,
    /// One-line description.
    pub description: String,
    /// SPDX license identifier.
    pub license: String,
    /// Canonical repository URL.
    pub repository: String,
    /// List of author strings (`"Name <email>"` or `"Name"`).
    pub authors: Vec<String>,
}

/// Error type for sync operations.
#[derive(Debug)]
pub enum SyncError {
    /// An I/O error occurred.
    Io(std::io::Error),
    /// The SSOT file could not be parsed.
    Parse(String),
    /// A required field is missing from `meta/project.toml`.
    MissingField(String),
}

impl std::fmt::Display for SyncError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(e) => write!(f, "I/O error: {e}"),
            Self::Parse(msg) => write!(f, "parse error: {msg}"),
            Self::MissingField(field) => write!(f, "missing field `{field}` in meta/project.toml"),
        }
    }
}

impl std::error::Error for SyncError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io(e) => Some(e),
            Self::Parse(_) | Self::MissingField(_) => None,
        }
    }
}

impl From<std::io::Error> for SyncError {
    fn from(e: std::io::Error) -> Self {
        Self::Io(e)
    }
}

// ---------------------------------------------------------------------------
// Parse SSOT
// ---------------------------------------------------------------------------

/// Parse `meta/project.toml` from the given workspace root.
///
/// # Errors
///
/// Returns `SyncError` if the file cannot be read, is not valid TOML, or is
/// missing required fields.
pub fn parse_meta(workspace_root: &Path) -> Result<ProjectMeta, SyncError> {
    let path = workspace_root.join("meta").join("project.toml");
    let text = std::fs::read_to_string(&path)?;
    parse_meta_str(&text)
}

/// Parse `meta/project.toml` from an in-memory string (useful for tests).
///
/// # Errors
///
/// Returns `SyncError` on TOML parse failure or missing required fields.
pub fn parse_meta_str(text: &str) -> Result<ProjectMeta, SyncError> {
    let value: Value =
        toml::from_str(text).map_err(|e: toml::de::Error| SyncError::Parse(e.to_string()))?;

    let project = value
        .get("project")
        .and_then(Value::as_table)
        .ok_or_else(|| SyncError::MissingField("[project]".to_string()))?;

    let get_str = |key: &str| -> Result<String, SyncError> {
        project
            .get(key)
            .and_then(Value::as_str)
            .map(str::to_owned)
            .ok_or_else(|| SyncError::MissingField(key.to_string()))
    };

    let authors: Vec<String> = project
        .get("authors")
        .and_then(Value::as_array)
        .ok_or_else(|| SyncError::MissingField("authors".to_string()))?
        .iter()
        .map(|v| {
            v.as_str()
                .map(str::to_owned)
                .ok_or_else(|| SyncError::Parse("authors must be strings".to_string()))
        })
        .collect::<Result<Vec<_>, _>>()?;

    Ok(ProjectMeta {
        name: get_str("name")?,
        version: get_str("version")?,
        description: get_str("description")?,
        license: get_str("license")?,
        repository: get_str("repository")?,
        authors,
    })
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

/// Generate the full content of `bindings/python/pyproject.toml` from SSOT.
///
/// The file is wholly managed; any local edits will be overwritten on sync.
#[must_use]
pub fn generate_pyproject(meta: &ProjectMeta) -> String {
    let authors_toml = meta
        .authors
        .iter()
        .map(|a| format!("  {{ name = \"{a}\" }}"))
        .collect::<Vec<_>>()
        .join(",\n");

    format!(
        r#"# >>> zuit-sync: managed (do not edit) >>>
# Generated by `cargo xtask sync` from meta/project.toml.
# <<< zuit-sync: end <<<

[build-system]
requires = ["maturin>=1.7,<2"]
build-backend = "maturin"

[project]
name = "{name}"
version = "{version}"
description = "{description}"
license = {{ text = "{license}" }}
readme = "README.md"
requires-python = ">=3.8"
authors = [
{authors_toml}
]

[project.urls]
Repository = "{repository}"

[project.scripts]
zuit = "zuit._cli:main"

[tool.maturin]
module-name = "zuit"
python-source = "python"
features = ["pyo3/extension-module"]
"#,
        name = meta.name,
        version = meta.version,
        description = meta.description,
        license = meta.license,
        authors_toml = authors_toml,
        repository = meta.repository,
    )
}

/// Generate the full content of `bindings/node/package.json` from SSOT.
///
/// The file is wholly managed; any local edits will be overwritten on sync.
/// This generates a launcher-only package that ships `bin/zuit.js` without
/// any native node module or napi-rs toolchain dependency.
#[must_use]
pub fn generate_package_json(meta: &ProjectMeta) -> String {
    let authors_str = meta.authors.join(", ");
    format!(
        r#"{{
  "_comment": "zuit-sync: generated by `cargo xtask sync` from meta/project.toml. Do not edit.",
  "name": "{name}",
  "version": "{version}",
  "description": "{description}",
  "license": "{license}",
  "author": "{authors_str}",
  "repository": {{
    "type": "git",
    "url": "{repository}"
  }},
  "bin": {{
    "zuit": "bin/zuit.js"
  }},
  "files": [
    "bin/zuit.js",
    "README.md",
    "LICENSE"
  ],
  "engines": {{
    "node": ">=18"
  }},
  "scripts": {{
    "test": "node --test bin/zuit.test.js"
  }}
}}
"#,
        name = meta.name,
        version = meta.version,
        description = meta.description,
        license = meta.license,
        authors_str = authors_str,
        repository = meta.repository,
    )
}

// ---------------------------------------------------------------------------
// Cargo.toml rewriter
// ---------------------------------------------------------------------------

/// The opening marker for the managed block in `Cargo.toml`.
pub const CARGO_MARKER_START: &str = "# >>> zuit-sync: managed (do not edit) >>>";
/// The closing marker for the managed block in `Cargo.toml`.
pub const CARGO_MARKER_END: &str = "# <<< zuit-sync: end <<<";

/// Rewrite the `[workspace.package]` managed block in a `Cargo.toml` string.
///
/// Replaces every line between `CARGO_MARKER_START` and `CARGO_MARKER_END`
/// (exclusive) with the managed fields from `meta`.  Lines outside the markers
/// are preserved verbatim.
///
/// # Errors
///
/// Returns `SyncError::Parse` if the markers are not found.
pub fn rewrite_cargo_toml(original: &str, meta: &ProjectMeta) -> Result<String, SyncError> {
    let authors_toml = meta
        .authors
        .iter()
        .map(|a| format!("\"{a}\""))
        .collect::<Vec<_>>()
        .join(", ");

    let managed_block = format!(
        "version = \"{version}\"\n\
         description = \"{description}\"\n\
         license = \"{license}\"\n\
         repository = \"{repository}\"\n\
         authors = [{authors_toml}]",
        version = meta.version,
        description = meta.description,
        license = meta.license,
        repository = meta.repository,
        authors_toml = authors_toml,
    );

    let start_pos = original
        .find(CARGO_MARKER_START)
        .ok_or_else(|| SyncError::Parse(format!("start marker not found: {CARGO_MARKER_START}")))?;

    let end_pos = original
        .find(CARGO_MARKER_END)
        .ok_or_else(|| SyncError::Parse(format!("end marker not found: {CARGO_MARKER_END}")))?;

    if end_pos <= start_pos {
        return Err(SyncError::Parse(
            "end marker appears before start marker".to_string(),
        ));
    }

    // The end marker begins on its own line; include the newline after start marker.
    let after_start = start_pos + CARGO_MARKER_START.len();
    // Skip to the start of the line containing the end marker.
    let before_end = end_pos;

    let mut result = String::with_capacity(original.len());
    result.push_str(&original[..after_start]);
    result.push('\n');
    result.push_str(&managed_block);
    result.push('\n');
    result.push_str(&original[before_end..]);

    // Ensure trailing newline.
    if !result.ends_with('\n') {
        result.push('\n');
    }

    Ok(result)
}

// ---------------------------------------------------------------------------
// High-level sync / check operations
// ---------------------------------------------------------------------------

/// Paths for the three managed files, relative to workspace root.
struct ManagedPaths {
    cargo_toml: PathBuf,
    pyproject_toml: PathBuf,
    package_json: PathBuf,
}

impl ManagedPaths {
    fn new(workspace_root: &Path) -> Self {
        Self {
            cargo_toml: workspace_root.join("Cargo.toml"),
            pyproject_toml: workspace_root.join("bindings/python/pyproject.toml"),
            package_json: workspace_root.join("bindings/node/package.json"),
        }
    }
}

/// Compute what each managed file should contain (does not write to disk).
///
/// Returns `(cargo_toml_content, pyproject_content, package_json_content)`.
///
/// # Errors
///
/// Returns `SyncError` if the SSOT file cannot be parsed or the `Cargo.toml`
/// marker block is missing.
pub fn compute_sync(
    workspace_root: &Path,
    meta: &ProjectMeta,
) -> Result<(String, String, String), SyncError> {
    let paths = ManagedPaths::new(workspace_root);

    let cargo_original = std::fs::read_to_string(&paths.cargo_toml)?;
    let cargo_new = rewrite_cargo_toml(&cargo_original, meta)?;
    let pyproject_new = generate_pyproject(meta);
    let package_json_new = generate_package_json(meta);

    Ok((cargo_new, pyproject_new, package_json_new))
}

/// Write the three managed files to disk.
///
/// # Errors
///
/// Returns `SyncError` on any I/O failure.
pub fn run_sync(workspace_root: &Path) -> Result<(), SyncError> {
    let meta = parse_meta(workspace_root)?;
    let (cargo_new, pyproject_new, package_json_new) = compute_sync(workspace_root, &meta)?;

    let paths = ManagedPaths::new(workspace_root);
    std::fs::write(&paths.cargo_toml, cargo_new)?;
    std::fs::write(&paths.pyproject_toml, pyproject_new)?;
    std::fs::write(&paths.package_json, package_json_new)?;

    Ok(())
}

/// Check whether the three managed files are already in sync with SSOT.
///
/// Returns `true` if every file already matches what `run_sync` would write,
/// `false` otherwise.  Does **not** write to disk.
///
/// # Errors
///
/// Returns `SyncError` on I/O or parse failure.
pub fn run_sync_check(workspace_root: &Path) -> Result<bool, SyncError> {
    let meta = parse_meta(workspace_root)?;
    let (cargo_new, pyproject_new, package_json_new) = compute_sync(workspace_root, &meta)?;

    let paths = ManagedPaths::new(workspace_root);

    let cargo_current = std::fs::read_to_string(&paths.cargo_toml)?;
    let pyproject_current = std::fs::read_to_string(&paths.pyproject_toml).unwrap_or_default();
    let package_json_current = std::fs::read_to_string(&paths.package_json).unwrap_or_default();

    Ok(cargo_current == cargo_new
        && pyproject_current == pyproject_new
        && package_json_current == package_json_new)
}

// ---------------------------------------------------------------------------
// verify-tag
// ---------------------------------------------------------------------------

/// Verify that `tag` matches the SSOT version.
///
/// Strips a leading `v` from the tag before comparing.
///
/// # Errors
///
/// Returns `SyncError` on SSOT parse failure.
pub fn verify_tag(workspace_root: &Path, tag: &str) -> Result<bool, SyncError> {
    let meta = parse_meta(workspace_root)?;
    let stripped = tag.strip_prefix('v').unwrap_or(tag);
    Ok(stripped == meta.version)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    const SAMPLE_META: &str = r#"
[project]
name = "zuit"
version = "0.1.0"
description = "Multi-language static analysis CLI."
license = "MIT"
repository = "https://github.com/example/zuit"
authors = ["Alice Example"]
"#;

    fn sample_meta() -> ProjectMeta {
        parse_meta_str(SAMPLE_META).expect("valid SSOT fixture")
    }

    // ------------------------------------------------------------------
    // parse_meta_str
    // ------------------------------------------------------------------

    #[test]
    fn parse_meta_roundtrip() {
        let meta = sample_meta();
        assert_eq!(meta.name, "zuit");
        assert_eq!(meta.version, "0.1.0");
        assert_eq!(meta.license, "MIT");
        assert_eq!(meta.authors, vec!["Alice Example"]);
    }

    #[test]
    fn parse_meta_missing_field_returns_error() {
        let bad = r#"[project]
name = "zuit"
"#;
        let err = parse_meta_str(bad).unwrap_err();
        assert!(matches!(err, SyncError::MissingField(_)));
    }

    #[test]
    fn parse_meta_invalid_toml_returns_error() {
        let err = parse_meta_str("not = [valid toml]]]").unwrap_err();
        assert!(matches!(err, SyncError::Parse(_)));
    }

    // ------------------------------------------------------------------
    // generate_pyproject (golden test)
    // ------------------------------------------------------------------

    #[test]
    fn generate_pyproject_golden() {
        let meta = sample_meta();
        let got = generate_pyproject(&meta);

        // Header markers present.
        assert!(got.contains("# >>> zuit-sync: managed"));
        assert!(got.contains("# <<< zuit-sync: end <<<"));
        // Build system.
        assert!(got.contains("maturin"));
        // Metadata fields.
        assert!(got.contains("name = \"zuit\""));
        assert!(got.contains("version = \"0.1.0\""));
        assert!(got.contains("license = { text = \"MIT\" }"));
        assert!(got.contains("Alice Example"));
        assert!(got.contains("https://github.com/example/zuit"));
        // Module name.
        assert!(got.contains("module-name = \"zuit\""));
        // project.scripts section for pip PATH wiring.
        assert!(got.contains("[project.scripts]"));
        assert!(got.contains("zuit = \"zuit._cli:main\""));
        // Ends with newline.
        assert!(got.ends_with('\n'));
        // LF-only line endings.
        assert!(!got.contains('\r'));
    }

    // ------------------------------------------------------------------
    // generate_package_json (golden test)
    // ------------------------------------------------------------------

    #[test]
    fn generate_package_json_golden() {
        let meta = sample_meta();
        let got = generate_package_json(&meta);

        // Managed comment.
        assert!(got.contains("zuit-sync"));
        // Fields.
        assert!(got.contains("\"name\": \"zuit\""));
        assert!(got.contains("\"version\": \"0.1.0\""));
        assert!(got.contains("\"license\": \"MIT\""));
        assert!(got.contains("Alice Example"));
        // Launcher-only: no napi, no main, no types.
        assert!(!got.contains("\"napi\""));
        assert!(!got.contains("\"main\""));
        assert!(!got.contains("\"types\""));
        // files array present with expected entries.
        assert!(got.contains("\"files\""));
        assert!(got.contains("\"bin/zuit.js\""));
        assert!(got.contains("\"README.md\""));
        assert!(got.contains("\"LICENSE\""));
        // test script wired.
        assert!(got.contains("\"test\": \"node --test bin/zuit.test.js\""));
        // Node engine.
        assert!(got.contains("\">=18\""));
        // Valid JSON.
        let parsed: serde_json::Value =
            serde_json::from_str(&got).expect("generated package.json must be valid JSON");
        assert_eq!(parsed["name"], "zuit");
        assert_eq!(parsed["version"], "0.1.0");
        // bin field for npm PATH wiring.
        assert!(got.contains("\"bin\""));
        assert!(got.contains("\"bin/zuit.js\""));
        assert_eq!(parsed["bin"]["zuit"], "bin/zuit.js");
        // Ends with newline.
        assert!(got.ends_with('\n'));
        // LF-only.
        assert!(!got.contains('\r'));
    }

    // ------------------------------------------------------------------
    // rewrite_cargo_toml (golden test)
    // ------------------------------------------------------------------

    const CARGO_FIXTURE: &str = r#"[workspace]
resolver = "3"
members = ["crates/xtask"]

[workspace.package]
edition = "2024"
rust-version = "1.93"
# >>> zuit-sync: managed (do not edit) >>>
version = "0.0.1"
license = "Apache-2.0"
# <<< zuit-sync: end <<<

[workspace.dependencies]
toml = "1"
"#;

    #[test]
    fn rewrite_cargo_toml_golden() {
        let meta = sample_meta();
        let got = rewrite_cargo_toml(CARGO_FIXTURE, &meta).expect("rewrite should succeed");

        // Old values gone.
        assert!(!got.contains("0.0.1"));
        assert!(!got.contains("Apache-2.0"));
        // New values present.
        assert!(got.contains("version = \"0.1.0\""));
        assert!(got.contains("license = \"MIT\""));
        assert!(got.contains("repository = \"https://github.com/example/zuit\""));
        assert!(got.contains("authors = [\"Alice Example\"]"));
        // Preserved lines still present.
        assert!(got.contains("edition = \"2024\""));
        assert!(got.contains("rust-version = \"1.93\""));
        assert!(got.contains("[workspace.dependencies]"));
        // Markers still present.
        assert!(got.contains(CARGO_MARKER_START));
        assert!(got.contains(CARGO_MARKER_END));
        // Ends with newline, LF-only.
        assert!(got.ends_with('\n'));
        assert!(!got.contains('\r'));
    }

    #[test]
    fn rewrite_cargo_toml_missing_start_marker_error() {
        let no_marker = "[workspace]\nmembers = []\n";
        let meta = sample_meta();
        let err = rewrite_cargo_toml(no_marker, &meta).unwrap_err();
        assert!(matches!(err, SyncError::Parse(_)));
    }

    // ------------------------------------------------------------------
    // sync-check: in-sync and divergent
    // ------------------------------------------------------------------

    fn make_workspace(tmp: &TempDir, cargo: &str, pyproject: &str, pkg_json: &str) {
        // meta/project.toml
        fs::create_dir_all(tmp.path().join("meta")).unwrap();
        fs::write(
            tmp.path().join("meta/project.toml"),
            SAMPLE_META.trim_start(),
        )
        .unwrap();

        // Cargo.toml
        fs::write(tmp.path().join("Cargo.toml"), cargo).unwrap();

        // bindings
        fs::create_dir_all(tmp.path().join("bindings/python")).unwrap();
        fs::create_dir_all(tmp.path().join("bindings/node")).unwrap();
        fs::write(tmp.path().join("bindings/python/pyproject.toml"), pyproject).unwrap();
        fs::write(tmp.path().join("bindings/node/package.json"), pkg_json).unwrap();
    }

    #[test]
    fn sync_check_returns_true_when_in_sync() {
        let tmp = TempDir::new().unwrap();
        let meta = sample_meta();
        let cargo_synced = rewrite_cargo_toml(CARGO_FIXTURE, &meta).unwrap();
        let pyproject_synced = generate_pyproject(&meta);
        let pkg_synced = generate_package_json(&meta);

        make_workspace(&tmp, &cargo_synced, &pyproject_synced, &pkg_synced);

        let in_sync = run_sync_check(tmp.path()).expect("check should not error");
        assert!(in_sync, "files written by sync should pass sync-check");
    }

    #[test]
    fn sync_check_returns_false_when_divergent() {
        let tmp = TempDir::new().unwrap();
        let meta = sample_meta();
        let cargo_synced = rewrite_cargo_toml(CARGO_FIXTURE, &meta).unwrap();

        // pyproject intentionally stale
        make_workspace(&tmp, &cargo_synced, "stale content", "{}");

        let in_sync = run_sync_check(tmp.path()).expect("check should not error");
        assert!(!in_sync, "stale pyproject.toml should fail sync-check");
    }

    #[test]
    fn run_sync_writes_correct_files() {
        let tmp = TempDir::new().unwrap();
        // Start with the fixture Cargo.toml (has markers, old values).
        fs::create_dir_all(tmp.path().join("meta")).unwrap();
        fs::write(
            tmp.path().join("meta/project.toml"),
            SAMPLE_META.trim_start(),
        )
        .unwrap();
        fs::write(tmp.path().join("Cargo.toml"), CARGO_FIXTURE).unwrap();
        fs::create_dir_all(tmp.path().join("bindings/python")).unwrap();
        fs::create_dir_all(tmp.path().join("bindings/node")).unwrap();

        run_sync(tmp.path()).expect("sync should succeed");

        let cargo = fs::read_to_string(tmp.path().join("Cargo.toml")).unwrap();
        assert!(cargo.contains("version = \"0.1.0\""));

        let pyproject =
            fs::read_to_string(tmp.path().join("bindings/python/pyproject.toml")).unwrap();
        assert!(pyproject.contains("name = \"zuit\""));

        let pkg = fs::read_to_string(tmp.path().join("bindings/node/package.json")).unwrap();
        assert!(pkg.contains("\"version\": \"0.1.0\""));
    }

    // ------------------------------------------------------------------
    // verify_tag
    // ------------------------------------------------------------------

    #[test]
    fn verify_tag_matches_with_v_prefix() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir_all(tmp.path().join("meta")).unwrap();
        fs::write(
            tmp.path().join("meta/project.toml"),
            SAMPLE_META.trim_start(),
        )
        .unwrap();
        assert!(verify_tag(tmp.path(), "v0.1.0").unwrap());
    }

    #[test]
    fn verify_tag_matches_without_v_prefix() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir_all(tmp.path().join("meta")).unwrap();
        fs::write(
            tmp.path().join("meta/project.toml"),
            SAMPLE_META.trim_start(),
        )
        .unwrap();
        assert!(verify_tag(tmp.path(), "0.1.0").unwrap());
    }

    #[test]
    fn verify_tag_mismatch_returns_false() {
        let tmp = TempDir::new().unwrap();
        fs::create_dir_all(tmp.path().join("meta")).unwrap();
        fs::write(
            tmp.path().join("meta/project.toml"),
            SAMPLE_META.trim_start(),
        )
        .unwrap();
        assert!(!verify_tag(tmp.path(), "v1.0.0").unwrap());
    }

    // ------------------------------------------------------------------
    // Self-check: real repo files are already in sync
    // ------------------------------------------------------------------

    #[test]
    fn real_repo_is_in_sync() {
        // Locate the workspace root relative to this file's CARGO_MANIFEST_DIR.
        let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        // crates/xtask → workspace root is two levels up.
        let workspace_root = manifest_dir
            .parent()
            .and_then(std::path::Path::parent)
            .expect("invariant: CARGO_MANIFEST_DIR has two parent directories");

        let in_sync =
            run_sync_check(workspace_root).expect("sync-check on real repo should not error");
        assert!(
            in_sync,
            "real repo managed files are out of sync with meta/project.toml — run `cargo xtask sync`"
        );
    }
}
