//! Implementation of the `zuit install-hook` subcommand.
//!
//! Generates a pre-commit git hook script in the nearest git repository root.

use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result, bail};

/// Content of the generated pre-commit hook.
const HOOK_CONTENT: &str = r#"#!/usr/bin/env sh
# zuit pre-commit hook — generated by `zuit install-hook`.
# Re-run with `zuit install-hook --force` to refresh.
set -e

# Get staged files (added / copied / modified).
STAGED=$(git diff --cached --name-only --diff-filter=ACM)
if [ -z "$STAGED" ]; then
  exit 0
fi

if ! command -v zuit >/dev/null 2>&1; then
  echo "zuit: binary not found on PATH; skipping pre-commit analysis." >&2
  exit 0
fi

# Run zuit against the repo; fail the commit on Medium+.
zuit analyze --fail-on medium --no-save .
"#;

/// Walks up from `start` looking for a `.git` directory or file.
///
/// Returns the repo root (the directory that contains `.git`), or
/// `None` if no `.git` entry is found before the filesystem root.
fn find_git_root(start: &Path) -> Option<PathBuf> {
    let mut current = start.to_path_buf();
    loop {
        if current.join(".git").exists() {
            return Some(current);
        }
        if !current.pop() {
            return None;
        }
    }
}

/// Installs the pre-commit hook into `<repo_root>/.git/hooks/pre-commit`.
///
/// If `force` is `false` and the hook already exists, returns an error
/// with a hint to pass `--force`.
///
/// On Unix the file is created with mode `0755`.  On non-Unix platforms the
/// file is written without setting the executable bit; a note is printed to
/// stdout asking the user to make it executable manually.
///
/// # Errors
///
/// - Returns an error if the `.git/hooks` directory cannot be created.
/// - Returns an error if the hook file already exists and `force` is `false`.
/// - Returns an error if writing the hook file fails.
pub fn install_hook(repo_root: &Path, force: bool) -> Result<PathBuf> {
    let hooks_dir = repo_root.join(".git").join("hooks");
    std::fs::create_dir_all(&hooks_dir)
        .with_context(|| format!("creating hooks dir {}", hooks_dir.display()))?;

    let hook_path = hooks_dir.join("pre-commit");

    if hook_path.exists() && !force {
        bail!(
            "pre-commit hook already exists at {}; use --force to overwrite",
            hook_path.display()
        );
    }

    std::fs::write(&hook_path, HOOK_CONTENT)
        .with_context(|| format!("writing hook file {}", hook_path.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        let mut perms = std::fs::metadata(&hook_path)
            .with_context(|| format!("reading metadata of {}", hook_path.display()))?
            .permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&hook_path, perms)
            .with_context(|| format!("setting permissions on {}", hook_path.display()))?;
    }

    #[cfg(not(unix))]
    {
        println!(
            "Note: could not set executable bit on non-Unix platform. \
             Please make {} executable manually (e.g. `chmod +x`).",
            hook_path.display()
        );
    }

    Ok(hook_path)
}

/// Runs the `install-hook` subcommand.
///
/// Locates the git repository root by walking up from the current working
/// directory, then delegates to [`install_hook`].
///
/// # Errors
///
/// Returns an error if the current directory is not inside a git repository,
/// or if [`install_hook`] fails.
pub fn run(force: bool) -> Result<i32> {
    let cwd = std::env::current_dir().context("determining current directory")?;
    let repo_root = find_git_root(&cwd)
        .ok_or_else(|| anyhow::anyhow!("not inside a git repository (no .git found)"))?;

    let hook_path = install_hook(&repo_root, force)?;

    println!("Installed pre-commit hook at {}", hook_path.display());
    Ok(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// Creates a temp dir with a `.git/` directory structure to simulate a repo root.
    fn make_fake_repo() -> TempDir {
        let tmp = TempDir::new().expect("tempdir");
        std::fs::create_dir_all(tmp.path().join(".git")).expect("create .git dir");
        tmp
    }

    #[test]
    fn writes_hook_to_pre_commit() {
        let tmp = make_fake_repo();
        let path = install_hook(tmp.path(), false).expect("install_hook should succeed");
        assert_eq!(path, tmp.path().join(".git/hooks/pre-commit"));
        assert!(path.exists(), "hook file must exist");
    }

    #[cfg(unix)]
    #[test]
    fn sets_executable_bit_on_unix() {
        use std::os::unix::fs::PermissionsExt as _;
        let tmp = make_fake_repo();
        let path = install_hook(tmp.path(), false).expect("install_hook should succeed");
        let mode = std::fs::metadata(&path)
            .expect("metadata")
            .permissions()
            .mode();
        assert!(mode & 0o111 != 0, "hook must be executable (mode={mode:o})");
    }

    #[test]
    fn errors_when_no_git_dir() {
        // Use a path under /tmp that is not inside a git repo.
        // We pass it directly as the repo root to install_hook (which doesn't
        // walk up — that is done by run()). The real guard against "not in a
        // git repo" is find_git_root, which we also test directly via a path
        // we know has no ancestor .git (the filesystem root).
        let found = find_git_root(std::path::Path::new("/"));
        assert!(
            found.is_none(),
            "should not find a git root starting from /"
        );
    }

    #[test]
    fn errors_if_hook_exists_without_force() {
        let tmp = make_fake_repo();
        // Install once successfully.
        install_hook(tmp.path(), false).expect("first install should succeed");
        // Second install without force should fail.
        let result = install_hook(tmp.path(), false);
        assert!(
            result.is_err(),
            "expected error when hook exists and force=false"
        );
        let msg = format!("{}", result.unwrap_err());
        assert!(
            msg.contains("--force"),
            "error message should mention --force, got: {msg}"
        );
    }

    #[test]
    fn overwrites_if_force_true() {
        let tmp = make_fake_repo();
        install_hook(tmp.path(), false).expect("first install");
        let result = install_hook(tmp.path(), true);
        assert!(result.is_ok(), "force=true should overwrite without error");
    }

    #[test]
    fn generated_content_contains_fail_on_medium() {
        let tmp = make_fake_repo();
        let path = install_hook(tmp.path(), false).expect("install_hook");
        let content = std::fs::read_to_string(&path).expect("read hook");
        assert!(
            content.contains("zuit analyze --fail-on medium"),
            "hook must contain 'zuit analyze --fail-on medium', got:\n{content}"
        );
    }
}
